# Generated by Django 3.1.1 on 2021-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('registration_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
